name: Example Workflow
on: [workflow_dispatch]
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub Run Number
        run: echo "GitHub Run Number: ${{ github.run_number }}"
